services:
  - type: web
    name: rfid-medical-system
    env: python
    plan: free
    pythonVersion: "3.11.4"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rfid_db
          property: connectionString
      - key: POETRY_VIRTUALENVS_CREATE
        value: "false"

databases:
  - name: rfid_db
    plan: free
